### ISSUE TITLE
Sorting with Ignoring Articles should not ignore articles of other languages (Die in English is a different word)

### ISSUE THREAD

**Issue by yuuzhan** [Komet/MediaElch#1582]
**Describe the bug**
Movie "Die Hard" sorting "Hard, Die" when ignoring articles due to German "Die" meaning "The" which is ignored.

**To Reproduce**
Set the locale to English (I use the following lines in my docker compose to set it as English)
```
            - LANG=en_CA.UTF-8
            - LC_ALL=en_CA.UTF-8
            - LANGUAGE=en_CA:en
```
Check "Ignore Articles when sorting)" in the General Settings section ( `IgnoreArticlesWhenSorting=true` in MediaElch.conf)
Go to Movies List
See Die Hard sorted under H for Hard, Die.

**Expected behavior**
When using English Locale, should not ignore non English words when sorting (Die Hard should not be Hard, Die in English).
Issue seems to stem from AdvancedSettings.cpp having one array for all articles, when it could be loaded based on the Locale loaded first.

**MediaElch Version:**
 - [x] 2.10.0 stable

**Operating System:**
 - [ ] Windows
 - [ ] macOS
 - [x] Linux (distribution: "Ubuntu 23.04")

**Additional context**
Full docker compose used:
```
    mediaelch:
        image: elgranloky/mediaelch
        container_name: mediaelch
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Toronto
            - TAKE_CONFIG_OWNERSHIP=1
            - CLEAN_TMP_DIR=1
            - SECURE_CONNECTION=0
            - VNC_PASSWORD=****
            - LANG=en_CA.UTF-8
            - LC_ALL=en_CA.UTF-8
            - LANGUAGE=en_CA:en
        volumes:
            - /config:/config/xdg/config/kvibes/
            - /movies:/movies
            - /tv:/tv
        ports:
            - 5800:5800
            - 5900:5900
        logging:
            options:
                max-file: "5"
                max-size: "10m"
        restart: unless-stopped
```
